# Site settings
title:       "Блог Рахима Давлеткалиева"
header_title: "Rakh.im"
email:       freetonik@gmail.com
author:      Рахим Давлеткалиев
description: "Блог Рахима Давлеткалиева"
baseurl:     ""
url:         "https://rakh.im"
date_format: "%-d.%m.%Y"

# Google services
google_analytics: "UA-1360700-19"
google_verification:

# Facebook
facebook_app_id: "125006834268789"

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username:
bitbucket_username:
stackoverflow_id:
twitter_username: freetonik
google_plus_id:
linkedin_username:
facebook_username: freetonik
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
instagram_username: freetonik

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    "/:title/"
paginate:     15
sass:
  compressed: true

# Gems
gems: [jekyll-paginate]